### ISSUE TITLE
anybody figured out some of these settings?

### ISSUE THREAD

**Issue by MBadberg** [latonita/tenda-reverse#10]
Hi,
i have the MW3 and digged a little into it.

Anybody found out yet, what these settings are for?

china_net.enable=1
login.domain_name=www.tendawifi.com
ad.enable=0

I've changed them and until now i could not see any differences on the routers neither my network.

And i could not figured out, what ucloud on the mw3 does. It started ucloud as a service listen on port 9000.

Would be nice, if we can figure that out :-)

Greetings
Markus

**Comment by crees** [comment]
I reckon www.tendawifi.com is going to be the web configuration URL, once they finally get it working.

ad.enable-- hm, Active Directory?  Ambitious!

**Comment by xifi-kif** [comment]
ad = advertising?

**Comment by MBadberg** [comment]
> 

Maybe... I sold these thingys and switched to unifi.
