### ISSUE TITLE
Filtering DHCPv6 packets

### ISSUE THREAD

**Issue by dguerri** [latonita/tenda-reverse#2]
Brilliant walkthrough!!

I am almost sure Nova is filtering DHCPv6 packets when in bridging mode, but without root access I can’t prove my theory...
Any chance you could add some additional info on ebtables/ip6tables?

**Comment by latonita** [comment]
@dguerri there is some more info added about `cfm` utility - so if this routing is configurable and configuration stored between reboots - maybe it can be changed with `cfm` then. Happy researching!
