### ISSUE TITLE
Remove WIFI backhaul fallback

### ISSUE THREAD

**Issue by SirLouen** [latonita/tenda-reverse#23]
I was wondering if anyone has been able to remove the WIFI backhaul fallback this devices have

Sometimes, I'm not sure what happens exactly, but I found many of these AP on Wireless mode instead of the Ethernet mode. I have to switch them off, and switch them back on. Generally this happen with the regular maintenaces they do automatically at 3AM according to the app. The go back but in Wireless mode. 

Anyone have found how to disable this behavior?

**Comment by SirLouen** [comment]
I have returned this s****y routers. Tenda official support cannot be worse.

**Comment by gingerbeardman** [comment]
Sounds like you bought the wrong item for your requirements.

Bye

**Comment by SirLouen** [comment]
> Sounds like you bought the wrong item for your requirements.
> 
> Bye

Yes, that is what happened. Theorically they support wired backhauls, but they work wrongly. Preferred mode of operation is clearly the classic wireless backhaul with just one main node connected to the Ethernet. Still I find them pretty expensive for how shitty they are. I've bought six units of ZyXEL WSM20 which are basically the same shit hardware wise, but they seem to be better coded for this purpose

I contacted twice Tenda support channels and 0 response from them. I've contacted ZyXEL, and they wrote me back in 24H with them maybe sending me DTS for this routers

I would not recommend these Tenda even to my worst enemy

**Comment by gingerbeardman** [comment]
OK, we get it, you're annoyed you've wasted your time. "These are crap because they do not do what I want them to even though they never said they could! I would not recommend them to my worse enemy even though the problem is really my research rather than the product!"

For me, the Tenda have worked well sine I bought them, but my expectations were aligned with how they function.

Best of luck with your new decision. I hope it works how you want it to!

**Comment by crees** [comment]
To be fair, I think @SirLouen does make a good point about Tenda's dreadful lack of support.

I don't think it's unreasonable to expect that a feature that works should work properly- although it's also a fair point that buying a WiFi mesh solution is the exact opposite of what you want :)

**Comment by SirLouen** [comment]
I think that @crees got the point. A feature that works, should work properly.

@gingerbeardman it's weird to think that I should have done a better research before purching these devices, for a functionality that should be working straight out of the box. 

> For me, the Tenda have worked well sine I bought them, but my expectations were aligned with how they function.

Still you could have bought a better product with a better research. Even Mercusys and Cudy products are better designed software-wise. And as **crees** said, the support from Tenda is dreadful. 

The best of luck is what you are going to need to not find any weird issues in the future, otherwise you are going to find yourself searching for an alternative and ditching them away.

**Comment by gingerbeardman** [comment]
> Still you could have bought a better product with a better research.

"Better" is subjective. The Tenda do exactly what I require, and my research before purchase highlighted that my requirements were aligned with their capabilities. Sure there are products that do more, or less, but I did not need them. 

I've contacted Tenda support 3 times and they got back to me every time: on two occasions it took them 1 day, and on one occasion it took them 5 days. In each of the three cases the support was resolved (user account recovery, firmware improved, firmware download outage).

**Comment by SirLouen** [comment]
> > Still you could have bought a better product with a better research.
> 
> "Better" is subjective. The Tenda do exactly what I require, and my research before purchase highlighted that my requirements were aligned with their capabilities. Sure there are products that do more, or less, but I did not need them.
> 
> I've contacted Tenda support 3 times and they got back to me every time: on two occasions it took them 1 day, and on one occasion it took them 5 days. In each of the three cases the support was resolved (user account recovery, firmware improved, firmware download outage).

Dude, you are a Tenda representative. Don't f**k me up.

I'm done here. Luck with your Tenda sales.

**Comment by gingerbeardman** [comment]
LOL.

Right, the only possible explanation is that I work for them!? 

Not that, you know, I'm a consumer and I bought the product that matched by requirements.

![image](https://user-images.githubusercontent.com/49612/228282728-1246de53-4031-4188-85a2-bc3272f92fee.png)
