### ISSUE TITLE
MW6 opensource

### ISSUE THREAD

**Issue by polesapart** [latonita/tenda-reverse#3]
Not sure you know, but perhaps there's something useful here: https://down.tendacn.com/uploadfile/Tenda-GPL/MW6.tar.gz

**Comment by latonita** [comment]
Thanks, nice! I will check it out, it wasn't there when I was doing research I believe.

**Comment by latonita** [comment]
ouch, i think i missed that for some reason, it was there for a while. Thanks again

**Comment by Neustradamus** [comment]
@latonita: Not only MW6, please look all:
- https://www.tendacn.com/download/list-10.html

**Comment by latonita** [comment]
@Neustradamus @polesapart pardon for necroposting, but..
do you by any chance have the file downloaded?  i know its been a while, but its not available anymore on web site

**Comment by Neustradamus** [comment]
@latonita: On here?
- https://www.tendacn.com/fr/download/list-9.html

**Comment by Neustradamus** [comment]
@latonita: On here?
- https://www.tendacn.com/us/download/list-9.html

**Comment by latonita** [comment]
> @latonita: On here?
> 
>     * https://www.tendacn.com/us/download/list-9.html

only docs there, no GPL source code unfortunately

**Comment by polesapart** [comment]
> @Neustradamus @polesapart pardon for necroposting, but.. do you by any chance have the file downloaded? i know its been a while, but its not available anymore on web site

Sure, here you go: https://www.dropbox.com/scl/fo/ydqeqweasb3ukpzxt3xqq/h?rlkey=1lgmpzyterash27otagskaar8&dl=0

**Comment by latonita** [comment]
> Sure, here you go

Thanks a lot. Downloaded files. I will put them on github
