### ISSUE TITLE
Forwarding ranges of ports

### ISSUE THREAD

**Issue by gingerbeardman** [latonita/tenda-reverse#5]
Thanks for taking the time to document your findings!

One thing I'd like to do that the app doesn't allow is forwarding ranges of ports, rather than single ports.

Any ideas?

**Comment by crees** [comment]
Hm, other than scripting? :)

**Comment by gingerbeardman** [comment]
I can do that, but what am I scripting?

**Comment by crees** [comment]
I'd just generate the cfm commands to make a port mapping for each port in the range.

**Comment by gingerbeardman** [comment]
I will look into whether to use DMZ or map many ports. Thanks all!
